
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-frontiers
owner: ucsb-cs156
repo_name: proj-frontiers
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-addGraphQLSchemas","number":595,"title":"Adding the Canvas and GitHub GraphQL Schemas for Use by the GraphQL plugin","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/595"},{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"592-job-filters-add-user-id-and-course-id-to-the-frontend","number":594,"title":"SH-job filters-add user id and course id to the frontend","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/594"},{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"591-job-filters-create-and-populate-the-userid-and-courseid-column-when-jobs-are-created","number":593,"title":"SH-job filters-create and populate the userid and courseid column when jobs are created","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/593"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-commitCsvSimple","number":583,"title":"Allowing the Downloading of Commits as a CSV","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/583"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-simplifiedDockerfile","number":567,"title":"Simplifying the Application Dockerfile","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/567"}]
