
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-frontiers
owner: ucsb-cs156
repo_name: proj-frontiers
pull_requests: [{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-canvas-token-enc","number":615,"title":"dp - Added canvas encryption to the backend and updated frontend accordingly.","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/615"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Division7-patch-2","number":613,"title":"Add update_spreadsheet input to deploy workflow","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/613"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-rateLimitTracking","number":605,"title":"Adding a Way to Track Remaining GitHub Rate Limits","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/605"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-simplifiedDockerfile","number":567,"title":"Simplifying the Application Dockerfile","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/567"}]
