
name: "00-all-checks-pass: Run all checks and make sure they pass"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
          
env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: read


jobs:
  call-workflow:
    uses: ucsb-cs156/workflows/.github/workflows/00-all-checks-pass.yml@main
    secrets: 
      GH_TOKEN: ${{ github.token }} # pass GH_TOKEN to called workflow