name: "15-backend-format: Format Java Files"

on:
  workflow_dispatch:
  pull_request:
    paths: [ src/**, .github/workflows/15-backend-format.yml ]
  push:
    branches: [ main ]
    paths: [ src/** , .github/workflows/15-backend-format.yml]

jobs:
  call-backend-format:
    uses: ucsb-cs156/workflows/.github/workflows/15-backend-format.yml@main
    with:
      JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }}
