name: "32-frontend-coverage: Frontend Coverage (vite/vitest)"

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**, .github/workflows/32-frontend-coverage.yml]
  push:
    branches: [main]
    paths: [frontend/**, .github/workflows/32-frontend-coverage.yml]

jobs:
  call-frontend-coverage:
    uses: ucsb-cs156/workflows/.github/workflows/32-frontend-coverage.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
