# Running this script will run a full mutation coverage report
# (not incremental) on the main branch.

name: "34-frontend-main-mutation-testing: Stryker JS Mutation Testing (JavaScript/Jest)"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [frontend/**, .github/workflows/34-frontend-main-mutation-testing.yml]

jobs:
  call-frontend-main-mutation-testing:
    uses: ucsb-cs156/workflows/.github/workflows/34-frontend-main-mutation-testing.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}