name: "35-frontend-format: JavaScript format checking"

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**, .github/workflows/35-frontend-format.yml]
  push:
    branches: [main]
    paths: [frontend/**, .github/workflows/35-frontend-format.yml]

jobs:
  call-frontend-format:
    uses: ucsb-cs156/workflows/.github/workflows/35-frontend-format.yml@main
