name: 42-deploy-dokku.yml
on:
  pull_request:
    types: [labeled]

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  has_deploy_label:
    name: Has Deploy Label
    runs-on: ubuntu-latest
    outputs:
      has-label: ${{ steps.has_deploy_label.outputs.has_deploy_label }}
    env:
      DEPLOY_LABEL: ${{ github.event.label.name }}
    steps:
      - name: "Check for Deploy Label"
        id: has_deploy_label
        run: |
          if [ "$DEPLOY_LABEL" == "Dokku Deploy" ]; then
            echo "has_deploy_label=true" >> "$GITHUB_OUTPUT"
          fi
  deploy:
    runs-on: ubuntu-latest
    needs: has_deploy_label
    if: needs.has_deploy_label.outputs.has-label == 'true'
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: "Deploy on Dokku"
        id: send_workflow_call
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ucsb-cs156-s25/dokku-sync/actions/workflows/00-sync-a-PR.yml/dispatches \
            -f ref='main' \
            -f "inputs[pr_url]=$PR_URL"
